APP_NAME: podai
APP_PORT: 8181


# Postgres DB
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: dpay
DB_USER: postgres
DB_PASSWORD: postgres
DB_MAX_IDLE_CONNECTIONS: 2
DB_MAX_POOL_SIZE: 5
DB_CONN_MAX_LIFE_TIME: 1000
DB_CONN_MAX_IDLE_TIME: 1000
