APP_NAME: podai
APP_PORT: 8181


# Postgres DB
DB_HOST: dpg-crr20io8fa8c739fpulg-a.singapore-postgres.render.com
DB_PORT: 5432
DB_NAME: podai
DB_USER: podai_user
DB_PASSWORD: 8i1bNdzK5jPCzv6152ff9MnJOPQMFHsC
DB_MAX_IDLE_CONNECTIONS: 2
DB_MAX_POOL_SIZE: 5
DB_CONN_MAX_LIFE_TIME: 1000
DB_CONN_MAX_IDLE_TIME: 1000
